wip

diff --git a/wsconf b/wsconf
--- a/wsconf
+++ b/wsconf
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 set -euo pipefail
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
-pkgs=(
+packages=(
+# BEGINNING_OF_PACKAGES
+  aerospace
   azure-cli
   colima
   discord
@@ -10,16 +13,28 @@ pkgs=(
   docker-compose
   font-meslo-for-powerlevel10k
   fzf
-  graphviz
-  go
   gh
+  go
+  graphviz
   jetbrains-toolbox
-  nikitabobko/tap/aerospace
+  jq
+  mitmproxy
   powerlevel10k
+  rsync
+  shellcheck
+  shfmt
+  sl
   tfenv
   visual-studio-code
+  yq
   zsh-autosuggestions
   zsh-syntax-highlighting
+# END_OF_PACKAGES
+)
+
+taps=(
+  domt4/autoupdate
+  nikitabobko/tap
 )
 
 function install_ohmyzsh() {
@@ -58,10 +73,6 @@ function install_homebrew() {
 function install_taps() {
 	tapped="$(brew tap)"
 
-	taps=(
-	  domt4/autoupdate
-	)
-
 	for t in "${taps[@]}"; do
 	  if echo "${tapped[@]}" | grep -qw "$t"; then
 	    echo "[✓] tap: $t"
@@ -74,7 +85,7 @@ function install_taps() {
 function install_brews() {
 	installed="$(brew list)"
 
-	for p in "${pkgs[@]}"; do
+	for p in "${packages[@]}"; do
 	  if ! echo "${installed[@]}" | grep -qw "$p"; then
       printf "[ ] brew: Installing %s...\r" "$p"
 	    brew install "$p" &> /dev/null
@@ -92,6 +103,29 @@ function ensure_line_in_file() {
     echo "$line" >> "$file"
   fi
 }
+
+# Handle 'add' subcommand
+if [[ ${1:-null} == 'add' ]]; then
+  pkg_to_add="$2"
+	installed="$(brew list)"
+  if echo "${installed[@]}" | grep -qw "$pkg_to_add"; then
+    echo "'$pkg_to_add' is already installed"
+    exit
+  fi
+  if ! brew search "$pkg_to_add" &> /dev/null; then
+    echo "Package '$pkg_to_add' not found via Homebrew"
+    exit
+  fi
+  echo "Adding '$pkg_to_add' to the list of packages"
+  start_line="$(grep -nm1 BEGINNING_OF_PACKAGES "$0" | cut -d: -f1)"
+  end_line="$(grep -nm1 END_OF_PACKAGES "$0" | cut -d: -f1)"
+  sed -i '' "${end_line}i\\
+  $pkg_to_add\\
+" "$0"
+  "$SCRIPT_DIR/sort_section.sh" "$(( start_line + 1))" "$end_line" "$0"
+  "$0"
+  exit
+fi
 
 install_homebrew
 install_ohmyzsh
